/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Text, useGLTF } from "@react-three/drei";
import Queen from "../Queen/Queen";
import Checkboard from "../Checkboard/Checkboard";
import Pawn from "../Pawn/Pawn";
import Rook from "../Rook/Rook";

export default function Chess(props) {
  const { nodes, materials } = useGLTF("./checkboard.glb");
  return (
    <>
      <group {...props} dispose={null}>
        <Queen />
        {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Queen_1.geometry}
        material={nodes.Queen_1.material}
        position={[-0.44, 0.18, 5.18]}
      /> */}
        <Checkboard />
        {/* <group position={[-9.14, 0, 3.88]} rotation={[0, 1.56, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials.Checker}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials.Material}
        />
      </group> */}
        {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pawn.geometry}
        material={materials["pawn white"]}
        position={[-3.28, 0.42, 4.93]}
        rotation={[Math.PI / 2, 0, 0]}
      /> */}
        <Pawn />
        <Rook />
        {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.rook.geometry}
        material={nodes.rook.material}
        position={[0.02, 0.25, -4.82]}
        scale={0.64}
      /> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.knight_top.geometry}
          material={nodes.knight_top.material}
          position={[0.01, 1.27, -2.27]}
          rotation={[0, -0.03, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bishop001.geometry}
          material={nodes.Bishop001.material}
          position={[0, 0.03, 0.12]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.KIng001.geometry}
          material={nodes.KIng001.material}
          position={[-0.42, 0.03, 2.8]}
          rotation={[0, -1.23, 0]}
        />
      </group>
      <Text
        characters="abcdefghijklmnopqrstuvwxyz0123456789!"
        position={[0, 10, 0]}
      >
        hello world!
      </Text>
    </>
  );
}

useGLTF.preload("./checkboard.glb");
